spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${properties.datasource.username}
    password: ${properties.datasource.password}
    url: jdbc:mysql://${properties.datasource.path}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    hikari:
      maximum-pool-size: 100
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth2.client.id}
            client-secret: ${oauth2.client.secret}
            redirect-uri: https://${properties.server.path}/login/oauth2/code/google
            scope:
              - email
              - profile
jwt:
  issuer: ${jwt.issuer.email}
  secret_key: ${jwt.secret.key}